services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: yapper

  yapper:
    build: .
    ports:
      - 3001:3000
    env_file:
      - .env.dev # Change to .env.production for Production
