/* eslint-disable typescript-sort-keys/interface */

export interface LanguageValues {
	LANGUAGE_ENABLED: {};
	LANGUAGE_ID: {};
	LANGUAGE_NAME: {};
	PARSE_REGEX: {};
	MS_OTHER: {};
	SECOND_ONE: {};
	SECOND_OTHER: {};
	SECOND_SHORT: {};
	MINUTE_ONE: {};
	MINUTE_OTHER: {};
	MINUTE_SHORT: {};
	HOUR_ONE: {};
	HOUR_OTHER: {};
	HOUR_SHORT: {};
	DAY_ONE: {};
	DAY_OTHER: {};
	DAY_SHORT: {};
	YEAR_ONE: {};
	YEAR_OTHER: {};
	YEAR_SHORT: {};
	CreateInstantInvite: {};
	KickMembers: {};
	BanMembers: {};
	Administrator: {};
	ManageChannels: {};
	ManageGuild: {};
	AddReactions: {};
	ViewAuditLog: {};
	PrioritySpeaker: {};
	Stream: {};
	ViewChannel: {};
	SendMessages: {};
	SendTTSMessages: {};
	ManageMessages: {};
	EmbedLinks: {};
	AttachFiles: {};
	ReadMessageHistory: {};
	MentionEveryone: {};
	UseExternalEmojis: {};
	ViewGuildInsights: {};
	Connect: {};
	Speak: {};
	MuteMembers: {};
	DeafenMembers: {};
	MoveMembers: {};
	UseVAD: {};
	ChangeNickname: {};
	ManageNicknames: {};
	ManageRoles: {};
	ManageWebhooks: {};
	ManageGuildExpressions: {};
	ManageEmojisAndStickers: {};
	UseApplicationCommands: {};
	RequestToSpeak: {};
	ManageEvents: {};
	ManageThreads: {};
	CreatePublicThreads: {};
	CreatePrivateThreads: {};
	UseExternalStickers: {};
	SendMessagesInThreads: {};
	UseEmbeddedActivities: {};
	ModerateMembers: {};
	ViewCreatorMonetizationAnalytics: {};
	UseSoundboard: {};
	UseExternalSounds: {};
	SendVoiceMessages: {};
	INVALID_ARGUMENT_TITLE: {};
	INVALID_PATH_TITLE: {};
	INVALID_PATH_DESCRIPTION: {};
	INTERNAL_ERROR_TITLE: {};
	INTERNAL_ERROR_DESCRIPTION: {};
	SENTRY_EVENT_ID_FOOTER: { eventId: any };
	NON_EXISTENT_APPLICATION_COMMAND_TITLE: { type: any };
	NON_EXISTENT_APPLICATION_COMMAND_DESCRIPTION: { type: any };
	MISSING_PERMISSIONS_BASE_TITLE: {};
	MISSING_PERMISSIONS_OWNER_ONLY_DESCRIPTION: { type: any };
	MISSING_PERMISSIONS_DEVELOPER_ONLY_DESCRIPTION: { type: any };
	MISSING_PERMISSIONS_USER_PERMISSIONS_ONE_DESCRIPTION: { missingPermissions: any; type: any };
	MISSING_PERMISSIONS_USER_PERMISSIONS_OTHER_DESCRIPTION: { missingPermissions: any; type: any };
	MISSING_PERMISSIONS_CLIENT_PERMISSIONS_ONE_DESCRIPTION: { missingPermissions: any; type: any };
	MISSING_PERMISSIONS_CLIENT_PERMISSIONS_OTHER_DESCRIPTION: { missingPermissions: any; type: any };
	TYPE_ON_COOLDOWN_TITLE: { type: any };
	TYPE_ON_COOLDOWN_DESCRIPTION: { type: any; formattedTime: any };
	COOLDOWN_ON_TYPE_TITLE: { type: any };
	COOLDOWN_ON_TYPE_DESCRIPTION: { type: any };
	AN_ERROR_HAS_OCCURRED_TITLE: {};
	AN_ERROR_HAS_OCCURRED_DESCRIPTION: {};
	PING_COMMAND_NAME: {};
	PING_COMMAND_DESCRIPTION: {};
	PING: {};
	PONG: { hostLatency: any };
	TRANSCRIBE_COMMAND_NAME: {};
	CONFIG_COMMAND_NAME: {};
	CONFIG_COMMAND_DESCRIPTION: {};
	CONFIG_COMMAND_AUTO_TRANSCRIPT_VOICE_MESSAGES_SUB_COMMAND_GROUP_NAME: {};
	CONFIG_COMMAND_AUTO_TRANSCRIPT_VOICE_MESSAGES_SUB_COMMAND_GROUP_DESCRIPTION: {};
	CONFIG_COMMAND_AUTO_TRANSCRIPT_VOICE_MESSAGES_SUB_COMMAND_GROUP_ENABLE_SUB_COMMAND_NAME: {};
	CONFIG_COMMAND_AUTO_TRANSCRIPT_VOICE_MESSAGES_SUB_COMMAND_GROUP_ENABLE_SUB_COMMAND_DESCRIPTION: {};
	CONFIG_COMMAND_AUTO_TRANSCRIPT_VOICE_MESSAGES_SUB_COMMAND_GROUP_DISABLE_SUB_COMMAND_NAME: {};
	CONFIG_COMMAND_AUTO_TRANSCRIPT_VOICE_MESSAGES_SUB_COMMAND_GROUP_DISABLE_SUB_COMMAND_DESCRIPTION: {};
	AUTO_TRANSCRIPT_VOICE_MESSAGES_ENABLED_TITLE: {};
	AUTO_TRANSCRIPT_VOICE_MESSAGES_ENABLED_DESCRIPTION: {};
	AUTO_TRANSCRIPT_VOICE_MESSAGES_DISABLED_TITLE: {};
	AUTO_TRANSCRIPT_VOICE_MESSAGES_DISABLED_DESCRIPTION: {};
	NO_VALID_ATTACHMENTS_ERROR: {};
	MESSAGE_STILL_BEING_TRANSCRIBED_ERROR: {};
	TRANSCRIBING: {};
	READ_MORE_BUTTON_LABEL: {};
	TRANSCRIBED_MESSAGE_BUTTON_LABEL: {};
}
